### ISSUE TITLE
Multiple request to same function can cause ArgumentNullException

### ISSUE THREAD

**Issue by dstenroejl** [dark-loop/functions-authorize#62]
Hi,

We have a Azure Function app following the isolated model and targeting .NET 8 and Azure Functions v4. In this we use the `DarkLoop.Azure.Functions.Authorization.Isolated` package version 4.1.1 in combination with the ASP.NET Core `Authorize` attribute for a HttpTrigger'ed function.

For this function we have noticed several occasions where we get the following in our logs in Azure:
```
System.ArgumentNullException: All elements in authorization data must be non-null. (Parameter 'authorizeData')
    at DarkLoop.Azure.Functions.Authorization.Internal.Check.NotNull(Object value, String name, String message)
    at DarkLoop.Azure.Functions.Authorization.FunctionAuthorizationMetadata.<>c.<AddAuthorizeData>b__21_0(IAuthorizeData x)
    at DarkLoop.Azure.Functions.Authorization.Internal.Check.All[T](IEnumerable`1 sequence, Action`1 action)
    at DarkLoop.Azure.Functions.Authorization.FunctionAuthorizationMetadata.AddAuthorizeData(IEnumerable`1 authorizeData)
    at DarkLoop.Azure.Functions.Authorization.FunctionAuthorizationMetadataCollection.GetMetadata(String functionName, Type declaringType)
    at DarkLoop.Azure.Functions.Authorization.FunctionAuthorizationMetadataCollection.GetMetadata(String functionName)
    at DarkLoop.Azure.Functions.Authorization.FunctionsAuthorizationProvider.GetAuthorizationAsync(String functionName, IAuthorizationPolicyProvider policyProvider)
    at DarkLoop.Azure.Functions.Authorization.FunctionsAuthorizationMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next)
    at Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore.FunctionsHttpProxyingMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in /mnt/vss/_work/1/s/extensions/Worker.Extensions.Http.AspNetCore/src/FunctionsMiddleware/FunctionsHttpProxyingMiddleware.cs:line 54
    at DarkLoop.Azure.Functions.Authorization.Metadata.FunctionsAuthorizationMetadataMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next)
    at Microsoft.Azure.Functions.Worker.FunctionsApplication.InvokeFunctionAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 89
    at Microsoft.Azure.Functions.Worker.Handlers.InvocationHandler.InvokeAsync(InvocationRequest request) in D:\a\_work\1\s\src\DotNetWorker.Grpc\Handlers\InvocationHandler.cs:line 88
```

After some investigation it seems to be related to situations where the Azure Function app is newly deployed and restarted, and hence it has to recollect (cache) the `FunctionAuthorizationMetadata`. If we then perform multiple request (in parallel) to our function, it is possible to reach a state where it keeps failing with an internal server error (500) and the `System.ArgumentNullException: All elements in authorization data must be non-null. (Parameter 'authorizeData')`.

We currently doesn't have a deterministic automated test to reproduce the issue. 

We can however reproduced it locally, by having a test that performs two http request in parallel to a HttpTrigger on which we have the `Authorize` attribute - but only if we also runs the Azure Function app with the debugger attached (I suspect it impacts the timing of the executed code).

**Comment by artmasa** [comment]
@dstenroejl, thanks for reporting this. I will take a look at it.

**Comment by artmasa** [comment]
@dstenroejl, I was able to reproduce your scenario. Based on what I have found, there's a race condition between `FunctionsAuthorizationMetadataMiddleware` and `FunctionsAuthorizationMiddleware`.
Metadata middleware collects authorization metadata, but it is not thread safe, authorization middleware on the other side is thread safe through `IFunctionsAuthorizationProvider`.

I'm adding thread safety to the first one to ensure metadata construction is thread safe by function ID. Once metadata is collected, no more locks are required. I will be publishing a preview version with fix soon.

**Comment by dstenroejl** [comment]
@artmasa Great, thank you so much for prioritizing this. As soon as there is a preview I will be sure to try in out in our end and give you feedback.

**Comment by artmasa** [comment]
@dstenroejl, preview version is out there: `4.1.2-preview-240818-2`
Please take a look at it and let me know about the results. I have tried it with many concurrent requests multiple times (restarting app) and have not been able to reproduce the scenario after the change.

**Comment by dstenroejl** [comment]
@artmasa thank you, I will try it out and let you know. Since we mostly experienced it in Azure I have to create a prerelease of our application and have it rolled out in our environments, where it will be deployed several times a day to get the best verification/feedback. We used to see it a few times a day on deployment, so if we let it deploy like this in two days and we haven't seen it, it should be fairly trustworthy.

**Comment by dstenroejl** [comment]
@artmasa it is looking good, we have deployed 7 times today without seeing the exception. :)

**Comment by artmasa** [comment]
@dstenroejl, that is awesome news! As soon as you feel confident, let me know and I will generate a release version of the package.

**Comment by dstenroejl** [comment]
@artmasa another day without exceptions, so I believe we can feel confident in using the updated version. When ever you have the time for releasing, we will be ready to update. :)

**Comment by artmasa** [comment]
@dstenroejl, will publish soon

**Comment by artmasa** [comment]
@dstenroejl, The packages have been published. They should be available soon.

**Comment by dstenroejl** [comment]
@artmasa great, we have updated to the latest version. Thank you again for prioritizing this and for you fix.

**Comment by artmasa** [comment]
You can close once you deploy and verify. Thanks again for reporting
